# Generated by Django 5.1 on 2024-09-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=120)),
                ('endereco_residencial', models.CharField(max_length=250)),
                ('cidade_moradia', models.CharField(max_length=100)),
                ('email_pessoal', models.EmailField(max_length=254)),
                ('nome_curso', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
